sudo: required
language: node_js
node_js: stable
# install:
#     - npm install -g vuepress
script: bash ./deploy.sh
    # - npm run build
cache:
    directories:
        - "node_modules"
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: docs/.vuepress/dist
    github-token: $access_token
    repo: xiaoxiaobingguai/notes
    keep-history: true
    target-branch: master:gh-pages
    on:
        branch: master
notifications:
  email: false
